device:
  "210":
    hostip: 192.168.1.212
    target_device_id: display_001
  # Add more devices as needed
  # "211":
  #   hostip: 192.168.1.213

alter_neko:
  mqtt_broker: 192.168.1.56
  mqtt_port: 1883
  mqtt_topic: display/alert

# AI Detection settings
detection:
  detector_count: 5  # Number of parallel YOLO detectors
  model_path: "models/best.mlpackage"
  confidence_threshold: 0.8
  analysis_interval: 0.5  # Interval in seconds between frame analysis